name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # Roda todo dia à meia-noite
  workflow_dispatch: # Permite rodar manualmente

permissions:
  contents: write # Permissão para enviar arquivos gerados

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Gerar cobrinha
        uses: Platane/snk@v3
        with:
          github_user_name: Lucas-RM
          outputs: |
            ./output/github-contribution-grid-snake.svg
            ./output/github-contribution-grid-snake-dark.svg?palette=github-dark
            ./output/github-contribution-grid-snake.gif
            ./output/github-contribution-grid-snake-dark.gif?palette=github-dark

      - name: Commit e push para o branch output
        run: |
          git config --global user.name "Lucas Marcondes"
          git config --global user.email "lucas.marcondes36@gmail.com"
          git add .
          git commit -m "Atualiza snake animation"
          git push origin main --force
